stages:
  - test

test:
  stage: test
  image:
    name: vsis/wea-test:latest
    entrypoint: [""]
  script:
    - make check
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    when: always
    paths:
      - coverage.xml
      - src/*.gcov
      - src/*.xml
    reports:
      junit: src/*.test.xml
      cobertura: coverage.xml
