name: check

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: criterion
      run: sudo apt-get install -y libcriterion-dev
    - name: make check
      run: make all check
      working-directory: ./src
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: src/*.xml
